import { Montserrat } from "next/font/google";
import "./globals.css";

const mont = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Atmospheric Particulate Matter Forecasting",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="th" className={mont.className}>
      <body>{children}</body>
    </html>
  );
}
